Nucleus\DataBaseSwitchBundle\Entity\Contact:
    type: entity
    table: null
    repositoryClass: Nucleus\DataBaseSwitchBundle\Entity\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        societe:
            type: string
            length: 255
    lifecycleCallbacks: {  }
